project_name: "DREEAM - RoBERTa - Combined - FINALIZED"
dataset_name: "Combined"
lambda_val: 0.28628900401230895
seed_val: 66
num_class: 120
meta_dir: "/work3/s174159/LLM_Thesis/data/Final/Combined/DREEAM_META"
data_dir: "/work3/s174159/LLM_Thesis/data/Final/Combined"
predictions_output: "/work3/s174159/LLM_Thesis/Results/DREEAM/ROBERTA_FINALIZED"