adafactor: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
amp_level: null
apply_early_stopping: false
attention_dropout: null
checkpoint_path: null
classifier: false
dataloader_drop_last: false
dataloader_num_workers: 0
dataloader_pin_memory: true
decoder_layerdrop: null
deepspeed: null
disable_tqdm: null
do_eval: true
do_predict: false
do_train: true
dropout: 0.1
eval_accumulation_steps: null
eval_batch_size: 8
eval_steps: null
evaluation_strategy: 'no'
fp16_backend: auto
fp16_opt_level: O1
gpus: 1
gradient_acc_steps: 8
gradient_accumulation_steps: 1
gradient_clip_value: 10.0
greater_is_better: null
group_by_length: false
ignore_data_skip: false
label_names: null
label_smoothing: 0.0
label_smoothing_factor: 0.0
learning_rate: 0.00016974550697981957
load_best_model_at_end: false
local_rank: -1
lr_scheduler: linear
max_grad_norm: 1
max_steps: 2000
metric_for_best_model: null
model_name: docred
monitor_var: val_F1_micro
monitor_var_mode: max
num_train_epochs: 5
offline_mode: false
past_index: -1
patience: 5
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
per_gpu_eval_batch_size: null
per_gpu_train_batch_size: null
precision: 16
predict_with_generate: false
prediction_loss_only: false
remove_unused_columns: true
run_name: null
samples_interval: 500
save_top_k: 3
seed: 42
sharded_ddp: false
sortish_sampler: false
train_batch_size: 8
val_check_interval: 1.0
val_percent_check: 1.0
warmup_steps: 1000
weight_decay: 0
